### ISSUE TITLE
Undefined variables in billmate_partpayment feature

### ISSUE THREAD

**Issue by kryllem** [Billmate/opencart#80] opened 2015-09-08 08:12 UTC
I'm getting following errors in errorlog:

Undefined variable: special in /xxx/vqmod/vqcache/vq2-system_modification_catalog_controller_product_category.php on line 441
Undefined variable: price in /xxx/vqmod/vqcache/vq2-system_modification_catalog_controller_product_category.php on line 441

**Comment by Boxedsolutions** [comment] 2015-09-08 08:23
We have noted this, we should release a fix for this in a short while. 

But for long if you want you can apply it your self find this line in billmate_partpayment.ocmod.xml:
                $payfrom = $this->model_payment_billmate_partpayment->getLowestPaymentFromTotal(($special) ? $special : $price);
Change to:
                $payfrom = $this->model_payment_billmate_partpayment->getLowestPaymentFromTotal(($result['special']) ? $result['special'] : $result['price']);

Upload it again in the modification system and refresh cache.

**Comment by kryllem** [comment] 2015-09-08 10:06
Ok, thanks

**Comment by kryllem** [comment] 2015-09-09 08:28
After change in code:
>Undefined variable: result in /xxx/vqmod/vqcache/vq2-system_modification_catalog_controller_product_category.php on line 441

**Comment by Boxedsolutions** [comment] 2015-09-09 08:29
Will check. But you can take a screenshot of the code before and around line 441 to help us to figure out the cause.

**Comment by kryllem** [comment] 2015-09-09 08:37
That is from vqcache:
![variable-result](https://cloud.githubusercontent.com/assets/13641326/9757092/a8c54a6c-56de-11e5-959d-88ab436927b7.jpg)

**Comment by Boxedsolutions** [comment] 2015-09-09 08:42
Check for the line above foreach($results as $result){ And post this to, it seems that something is changed there in your file.

**Comment by kryllem** [comment] 2015-09-09 08:50
![foreach-results-1](https://cloud.githubusercontent.com/assets/13641326/9757370/86a495ee-56e0-11e5-8941-562377c8001e.jpg)
![foreach-results-2](https://cloud.githubusercontent.com/assets/13641326/9757375/8b56a190-56e0-11e5-9a12-ec431219c4f3.jpg)

**Comment by Boxedsolutions** [comment] 2015-09-09 09:28
Lets see below that, its not that standard as far as I see. 

I will find it but it might bee easier if you just drop me a email at jesper[at]boxedsolutions.se with the whole file. Both the vq cache file and the original, so I can review it and see what changes we need.

**Comment by kryllem** [comment] 2015-09-09 09:34
Ok, I will send you those files.

**Comment by Boxedsolutions** [comment] 2015-09-09 09:54
Great, I think you can change the billmate_partpayment.ocmod.xml to 
like this as its more than one occurence of the search phrase for our mod. 
note that I added index=1 to make ocmod only search for first result.

    <file path="catalog/controller/product/category.php">
        <operation>
            <search index="1">
                <![CDATA[
                if ($this->config->get('config_review_status')) {
            ]]>
            </search>
            <add position="before">

**Comment by kryllem** [comment] 2015-09-09 20:31
Changing caused following error:
>Undefined variable: billmate_payfrom in /xxx/vqmod/vqcache/vq2-system_modification_catalog_controller_product_category.php on line 369

Appeared 12 times

**Comment by Boxedsolutions** [comment] 2015-09-10 08:52
Ok, it seems to be better to use this code: 
<file path="catalog/controller/product/category.php">
        <operation>
            <search>
                <![CDATA[
                if ($this->config->get('config_tax')) {
            ]]>
            </search>

Note I search for if ($this->config->get('config_tax')) { which should only be once in the file and it should work I guess.

**Comment by kryllem** [comment] 2015-09-11 12:33
This code seem to solve the problem.
Thanks!

**Closed** 2015-09-15 19:47 UTC
Labels: 2.0, bug
